Traceback (most recent call last):
  File "main.py", line 63, in <module>
    with open('./results/samples/data_set_'+str(cz)+'.csv', 'wb') as csvfile:
IOError: [Errno 2] No such file or directory: './results/samples/data_set_3A.csv'
